#!/usr/bin/env python3
"""Loopback 3DGS RGB camera bridge; open /bridge in one WebGL-capable browser.

POST /render with {id, cam_pos:[x,y,z], cam_forward:[x,y,z], cam_up:[x,y,z]}.
The response is an actual 320x240 PNG from the browser, with X-Frame-Id.
Camera vectors use the original scene's metric, +Z-up coordinates. No depth,
collision labels or substitute rendering are generated by this service.
"""
from __future__ import annotations

import argparse
from collections import deque
from dataclasses import dataclass, field
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
import json
import math
from pathlib import Path
import re
import struct
import threading
import time
from urllib.parse import parse_qs, urlsplit
import uuid
import zlib

ROOT = Path(__file__).resolve().parents[1]
FILES = {
    "/": (ROOT / "dashboard/render-bridge.html", "text/html; charset=utf-8"),
    "/bridge": (ROOT / "dashboard/render-bridge.html", "text/html; charset=utf-8"),
    "/scene/robot_hall.ply": (ROOT / "models/gaussian/robot_hall.ply", "application/octet-stream"),
    "/lib/three.module.js": (ROOT / "dashboard/lib/three.module.js", "text/javascript"),
    "/lib/gaussian-splats-3d.module.js": (ROOT / "dashboard/lib/gaussian-splats-3d.module.js", "text/javascript"),
    "/live.jpg": (ROOT / "outputs/realistic/live.jpg", "image/jpeg"),
    "/results": (ROOT / "dashboard/realistic-results.html", "text/html; charset=utf-8"),
    "/explore": (ROOT / "dashboard/explore.html", "text/html; charset=utf-8"),
    "/evaluation.mp4": (ROOT / "outputs/realistic/avoidance-pilot.mp4", "video/mp4"),
    "/distance-probe.png": (ROOT / "outputs/realistic/distance-probe.png", "image/png"),
    "/proxy-overlay.png": (ROOT / "outputs/realistic/proxy-overlay.png", "image/png"),
    "/obstacle-inspection.png": (ROOT / "outputs/realistic/obstacle-inspection.png", "image/png"),
}
for index in range(4):
    FILES[f"/obstacle-view-{index}.png"] = (
        ROOT / f"outputs/realistic/obstacle-view-{index}.png", "image/png")
for report in ("avoidance-audit.json", "distance-probe.json", "renderer-performance.json", "distance-data-provenance.json"):
    FILES["/" + report] = (ROOT / "outputs/realistic" / report, "application/json; charset=utf-8")
FRAME_TIMEOUT = 45.0
OFFER_LEASE_SECONDS = 2.0
MAX_PNG_BYTES = 1024 * 1024


@dataclass
class Job:
    request: dict
    created: float = field(default_factory=time.monotonic)
    done: threading.Event = field(default_factory=threading.Event)
    dispatched: bool = False
    offered_at: float = 0.0
    lease_token: str | None = None
    claimed: bool = False
    png: bytes | None = None
    error: str | None = None


class Bridge:
    def __init__(self):
        self.condition = threading.Condition()
        self.jobs: dict[str, Job] = {}
        self.recent_ids = deque(maxlen=1024)
        self.ready = False
        self.browser_seen = 0.0
        self.completed = 0
        self.failures = 0
        self.last_frame_id = None
        self.reoffers = 0


def frame_id(value):
    if isinstance(value, bool) or not isinstance(value, (str, int)):
        raise ValueError("id must be a string or integer")
    value = str(value)
    if not re.fullmatch(r"[A-Za-z0-9._:-]{1,96}", value):
        raise ValueError("id must contain 1-96 letters, digits, '.', '_', ':' or '-'")
    return value


def vector(value, name, max_abs):
    if not isinstance(value, list) or len(value) != 3:
        raise ValueError(f"{name} must be an array of three numbers")
    if any(isinstance(x, bool) or not isinstance(x, (int, float)) for x in value):
        raise ValueError(f"{name} must contain numbers")
    result = [float(x) for x in value]
    if any(not math.isfinite(x) or abs(x) > max_abs for x in result):
        raise ValueError(f"{name} contains a non-finite or out-of-bounds coordinate")
    return result


def validate_request(data):
    if not isinstance(data, dict):
        raise ValueError("request must be a JSON object")
    ident = frame_id(data.get("id"))
    pos = vector(data.get("cam_pos"), "cam_pos", 1000)
    forward = vector(data.get("cam_forward"), "cam_forward", 1000)
    up = vector(data.get("cam_up"), "cam_up", 1000)
    fn = math.sqrt(sum(x * x for x in forward))
    un = math.sqrt(sum(x * x for x in up))
    if fn < 1e-8 or un < 1e-8:
        raise ValueError("camera forward and up must be non-zero")
    forward = [x / fn for x in forward]
    up = [x / un for x in up]
    if abs(sum(a * b for a, b in zip(forward, up))) > 0.999:
        raise ValueError("camera forward and up cannot be parallel")
    return dict(id=ident, cam_pos=pos, cam_forward=forward, cam_up=up)


def validate_png(body):
    if not 45 <= len(body) <= MAX_PNG_BYTES or body[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("frame must be a PNG smaller than 1 MiB")
    offset = 8
    chunks = []
    while offset + 12 <= len(body):
        length = struct.unpack_from(">I", body, offset)[0]
        kind = body[offset + 4:offset + 8]
        end = offset + 12 + length
        if end > len(body):
            raise ValueError("truncated PNG chunk")
        payload = body[offset + 8:offset + 8 + length]
        expected = struct.unpack_from(">I", body, offset + 8 + length)[0]
        if zlib.crc32(kind + payload) & 0xFFFFFFFF != expected:
            raise ValueError("invalid PNG checksum")
        if not chunks:
            if kind != b"IHDR" or length != 13:
                raise ValueError("PNG must begin with IHDR")
            width, height, bits, color, compression, filtering, interlace = struct.unpack(">IIBBBBB", payload)
            if (width, height) != (320, 240) or bits != 8 or color not in (2, 6):
                raise ValueError("PNG must be 320x240 with 8-bit RGB or RGBA")
            if compression or filtering or interlace:
                raise ValueError("PNG encoding unsupported")
        chunks.append(kind)
        offset = end
        if kind == b"IEND":
            if length or offset != len(body) or b"IDAT" not in chunks:
                raise ValueError("invalid PNG ending")
            return
    raise ValueError("PNG missing IEND")


class Handler(BaseHTTPRequestHandler):
    @property
    def bridge(self):
        return self.server.bridge

    def log_message(self, fmt, *args):
        # High-volume frame and poll traffic stays quiet; explicit failures remain visible.
        if args and str(args[1] if len(args) > 1 else "").startswith(("4", "5")):
            super().log_message(fmt, *args)

    def reply(self, status, body=b"", kind="application/json", headers=None):
        self.send_response(status)
        self.send_header("Content-Type", kind)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-Content-Type-Options", "nosniff")
        for key, value in (headers or {}).items():
            self.send_header(key, str(value))
        self.end_headers()
        try:
            self.wfile.write(body)
        except (BrokenPipeError, ConnectionResetError):
            pass

    def json_reply(self, status, data):
        self.reply(status, json.dumps(data, allow_nan=False).encode())

    def read_body(self, maximum):
        try:
            length = int(self.headers.get("Content-Length", "-1"))
        except ValueError as exc:
            raise ValueError("invalid Content-Length") from exc
        if not 0 <= length <= maximum:
            raise ValueError("request body is missing or too large")
        self.connection.settimeout(10)
        body = self.rfile.read(length)
        if len(body) != length:
            raise ValueError("incomplete request body")
        return body

    def do_GET(self):
        route = urlsplit(self.path).path
        if route in FILES:
            path, kind = FILES[route]
            try:
                body = path.read_bytes()
            except FileNotFoundError:
                self.json_reply(503, {"error": "Required local asset is missing"})
                return
            self.reply(200, body, kind)
        elif route == "/results.json":
            result = {}
            for key, name in (("avoidance", "avoidance-audit.json"), ("distance", "distance-probe.json"), ("status", "status.json")):
                try:
                    result[key] = json.loads((ROOT / "outputs/realistic" / name).read_text())
                except (FileNotFoundError, json.JSONDecodeError):
                    result[key] = None
            self.json_reply(200, result)
        elif route == "/status":
            try:
                data = json.loads((ROOT / "outputs/realistic/status.json").read_text())
            except (FileNotFoundError, json.JSONDecodeError):
                data = {"phase": "waiting", "message": "等待 Python 實驗啟動", "completed": 0, "total": 0}
            self.json_reply(200, data)
        elif route == "/health":
            with self.bridge.condition:
                state = dict(ready=self.bridge.ready, pending=len(self.bridge.jobs),
                             completed=self.bridge.completed, failures=self.bridge.failures,
                             last_frame_id=self.bridge.last_frame_id, reoffers=self.bridge.reoffers,
                             claimed=sum(job.claimed and not job.done.is_set() for job in self.bridge.jobs.values()),
                             browser_seconds_ago=(round(time.monotonic() - self.bridge.browser_seen, 2)
                                                  if self.bridge.browser_seen else None),
                             width=320, height=240, fov_y=85, renderer="GaussianSplats3D WebGL")
            self.json_reply(200, state)
        elif route == "/next":
            deadline = time.monotonic() + 20
            offer = None
            with self.bridge.condition:
                self.bridge.browser_seen = time.monotonic()
                while time.monotonic() < deadline:
                    now = time.monotonic()
                    for candidate in self.bridge.jobs.values():
                        if candidate.done.is_set() or candidate.claimed:
                            continue
                        # A tab reload can abandon a long poll after its response
                        # has been written. Offers need an explicit browser claim.
                        if not candidate.dispatched or now - candidate.offered_at >= OFFER_LEASE_SECONDS:
                            if candidate.dispatched:
                                self.bridge.reoffers += 1
                            candidate.dispatched = True
                            candidate.offered_at = now
                            candidate.lease_token = uuid.uuid4().hex
                            offer = dict(candidate.request, lease_token=candidate.lease_token,
                                         lease_seconds=OFFER_LEASE_SECONDS)
                            break
                    if offer:
                        break
                    self.bridge.condition.wait(min(0.25, max(0, deadline - time.monotonic())))
            if offer:
                self.json_reply(200, offer)
            else:
                self.reply(204)
        else:
            self.json_reply(404, {"error": "Unknown route"})

    def do_POST(self):
        # Browser fetches are same-origin; no public CORS API is exposed.
        origin = self.headers.get("Origin")
        allowed = {f"http://127.0.0.1:{self.server.server_port}", f"http://localhost:{self.server.server_port}"}
        if origin and origin not in allowed:
            self.json_reply(403, {"error": "Only same-origin requests are accepted"})
            return
        url = urlsplit(self.path)
        try:
            if url.path == "/render":
                request = validate_request(json.loads(self.read_body(4096)))
                self.render_request(request)
            elif url.path == "/claim":
                data = json.loads(self.read_body(4096))
                ident = frame_id(data.get("id"))
                token = str(data.get("lease_token", ""))
                with self.bridge.condition:
                    job = self.bridge.jobs.get(ident)
                    if not job or not job.dispatched or job.claimed or job.done.is_set() or job.lease_token != token:
                        self.json_reply(409, {"error": "Offer has expired, was already claimed or is no longer active"})
                        return
                    job.claimed = True
                    self.bridge.browser_seen = time.monotonic()
                self.json_reply(200, {"id": ident, "claimed": True})
            elif url.path == "/frame":
                query = parse_qs(url.query)
                ident = frame_id(query.get("id", [None])[0])
                token = query.get("lease_token", [""])[0]
                body = self.read_body(MAX_PNG_BYTES)
                validate_png(body)
                self.accept_frame(ident, token, body)
            elif url.path == "/error":
                query = parse_qs(url.query)
                ident = frame_id(query.get("id", [None])[0])
                token = query.get("lease_token", [""])[0]
                data = json.loads(self.read_body(4096))
                with self.bridge.condition:
                    job = self.bridge.jobs.get(ident)
                    if not job or not job.claimed or job.done.is_set() or job.lease_token != token:
                        self.json_reply(409, {"error": "No active frame with this id"})
                        return
                    job.error = str(data.get("error", "Browser rendering failed"))[:1000]
                    job.done.set()
                self.json_reply(200, {"id": ident})
            elif url.path == "/ready":
                data = json.loads(self.read_body(4096))
                with self.bridge.condition:
                    self.bridge.ready = data.get("ready") is True
                    self.bridge.browser_seen = time.monotonic()
                self.json_reply(200, {"ok": True})
            else:
                self.json_reply(404, {"error": "Unknown route"})
        except (ValueError, TypeError, TimeoutError) as exc:
            self.json_reply(400, {"error": str(exc)})

    def render_request(self, request):
        ident = request["id"]
        with self.bridge.condition:
            if ident in self.bridge.jobs or ident in self.bridge.recent_ids:
                self.json_reply(409, {"error": "Frame id already used; generate a new id"})
                return
            if len(self.bridge.jobs) >= 8:
                self.json_reply(429, {"error": "Render queue full"})
                return
            job = Job(request)
            self.bridge.jobs[ident] = job
            self.bridge.condition.notify_all()
        job.done.wait(FRAME_TIMEOUT)
        with self.bridge.condition:
            self.bridge.jobs.pop(ident, None)
            self.bridge.recent_ids.append(ident)
            if job.png is not None:
                self.bridge.completed += 1
                self.bridge.last_frame_id = ident
            else:
                self.bridge.failures += 1
        if job.png is not None:
            self.reply(200, job.png, "image/png", {"X-Frame-Id": ident, "X-Image-Width": 320,
                                                   "X-Image-Height": 240, "X-Renderer": "3DGS-WebGL"})
        elif job.error:
            self.json_reply(502, {"id": ident, "error": job.error})
        else:
            self.json_reply(504, {"id": ident, "error": "No browser frame within 45 seconds; open /bridge"})

    def accept_frame(self, ident, token, body):
        with self.bridge.condition:
            job = self.bridge.jobs.get(ident)
            if not job or not job.claimed or job.done.is_set() or job.lease_token != token:
                self.json_reply(409, {"error": "Frame is stale, duplicate or was never dispatched"})
                return
            job.png = body
            self.bridge.browser_seen = time.monotonic()
            job.done.set()
        self.json_reply(200, {"id": ident, "accepted": True})


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--port", type=int, default=8768)
    args = parser.parse_args()
    server = ThreadingHTTPServer(("127.0.0.1", args.port), Handler)
    server.daemon_threads = True
    server.bridge = Bridge()
    print(f"Actual 3DGS RGB camera bridge: http://127.0.0.1:{args.port}/bridge", flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
